title: BCDevExchange Platform Services
email: pathfinder@gov.bc.ca
description: >- # this means to ignore newlines until "baseurl:"
  Platform Services is a dedicated team providing high level administration and oversight to the BC Gov's DevOps Platform.

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: do-we-have-twitter
github_username:  bcgov

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true

# Additional collections other than posts.
collections:
  updates:
    output: true
  posts:
    output: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - .gitignore
  - LICENSE
